export type JsonHookDocument = Record<string, unknown>;

export type JsonHookConfigSpec<EventName extends string> = {
  /** Events for which Station installs one generated command entry. */
  eventNames: readonly EventName[];
  /** Extracts command objects from one provider event entry. */
  entryCommands(entry: unknown): readonly unknown[] | undefined;
  /** Rebuilds an event entry after generated commands have been removed. */
  withEntryCommands(entry: unknown, commands: readonly unknown[]): unknown | undefined;
  /** Extracts the exact executable path from one provider command object. */
  commandPath(command: unknown): string | undefined;
  /** Identifies commands generated by any supported Station version. */
  isGeneratedCommand(command: unknown): boolean;
  /** Creates one provider-native event entry for an exact command path. */
  createEntry(eventName: EventName, command: string): unknown;
  /** Removes generated commands from unknown event keys as well as managed events. */
  cleanupAllEvents?: boolean;
};

/** Shared generated-entry operations over a provider-owned JSON hooks document. */
export interface JsonHookConfigEditor<
  EventName extends string,
  Document extends JsonHookDocument = JsonHookDocument,
> {
  installCommands(document: Document, commands: Record<EventName, string>): Document;
  removeGeneratedCommands(
    document: Document,
    commands?: Partial<Record<EventName, string>>,
  ): Document;
  missingEvents(document: Document, commands: Record<EventName, string>): EventName[];
  generatedEvents(document: Document): string[];
  generatedCommands(document: Document): Record<EventName, string[]>;
  documentContainsCommand(document: Document, command: string): boolean;
}

/** Returns whether an untrusted JSON value is a non-array object. */
export function isJsonObject(value: unknown): value is JsonHookDocument {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function hooksOf(document: JsonHookDocument): JsonHookDocument | undefined {
  return isJsonObject(document.hooks) ? document.hooks : undefined;
}

function entriesOf(hooks: JsonHookDocument | undefined, eventName: string): unknown[] {
  const entries = hooks?.[eventName];
  return Array.isArray(entries) ? entries : [];
}

function removeGeneratedEntries<EventName extends string, Document extends JsonHookDocument>(
  spec: JsonHookConfigSpec<EventName>,
  document: Document,
  expectedCommands: Partial<Record<EventName, string>>,
): Document {
  const hooks = hooksOf(document);
  if (hooks === undefined) return document;

  const expectedPaths = new Set(Object.values(expectedCommands));
  const managedEvents = new Set<string>(spec.eventNames);
  const cleanedHooks: JsonHookDocument = {};
  for (const [eventName, value] of Object.entries(hooks)) {
    if ((!spec.cleanupAllEvents && !managedEvents.has(eventName)) || !Array.isArray(value)) {
      cleanedHooks[eventName] = value;
      continue;
    }
    const cleanedEntries = value.flatMap((entry) => {
      const commands = spec.entryCommands(entry);
      if (commands === undefined) return [entry];
      const remaining = commands.filter((command) => {
        const path = spec.commandPath(command);
        return (
          !spec.isGeneratedCommand(command) && (path === undefined || !expectedPaths.has(path))
        );
      });
      if (remaining.length === commands.length) return [entry];
      const cleaned = spec.withEntryCommands(entry, remaining);
      return cleaned === undefined ? [] : [cleaned];
    });
    if (cleanedEntries.length > 0) cleanedHooks[eventName] = cleanedEntries;
  }

  if (Object.keys(cleanedHooks).length > 0) return { ...document, hooks: cleanedHooks } as Document;
  const { hooks: _hooks, ...cleaned } = document;
  return cleaned as Document;
}

/**
 * ADAPTER
 *
 * Builds JSON hook mutation operations while providers retain command schemas,
 * generated-command detection, and event-entry shapes.
 */
export function createJsonHookConfigEditor<
  EventName extends string,
  Document extends JsonHookDocument = JsonHookDocument,
>(spec: JsonHookConfigSpec<EventName>): JsonHookConfigEditor<EventName, Document> {
  const entryHasCommand = (entry: unknown, command: string): boolean =>
    spec.entryCommands(entry)?.some((candidate) => spec.commandPath(candidate) === command) ===
    true;

  const entryHasGeneratedCommand = (entry: unknown): boolean =>
    spec.entryCommands(entry)?.some(spec.isGeneratedCommand) === true;

  const removeGeneratedCommands = (
    document: Document,
    expectedCommands: Partial<Record<EventName, string>> = {},
  ): Document => removeGeneratedEntries(spec, document, expectedCommands);

  return {
    installCommands: (document, commands) => {
      const cleaned = removeGeneratedCommands(document, commands);
      const hooks: JsonHookDocument = { ...(hooksOf(cleaned) ?? {}) };
      for (const eventName of spec.eventNames) {
        hooks[eventName] = [
          ...entriesOf(hooks, eventName),
          spec.createEntry(eventName, commands[eventName]),
        ];
      }
      return { ...cleaned, hooks } as Document;
    },
    removeGeneratedCommands,
    missingEvents: (document, commands) => {
      const hooks = hooksOf(document);
      return spec.eventNames.filter(
        (eventName) =>
          !entriesOf(hooks, eventName).some((entry) => entryHasCommand(entry, commands[eventName])),
      );
    },
    generatedEvents: (document) => {
      const hooks = hooksOf(document);
      return Object.keys(hooks ?? {})
        .filter((eventName) =>
          entriesOf(hooks, eventName).some((entry) => entryHasGeneratedCommand(entry)),
        )
        .sort((left, right) => left.localeCompare(right));
    },
    generatedCommands: (document) => {
      const hooks = hooksOf(document);
      const generated: Partial<Record<EventName, string[]>> = {};
      for (const eventName of spec.eventNames) {
        generated[eventName] = entriesOf(hooks, eventName).flatMap((entry) =>
          (spec.entryCommands(entry) ?? []).flatMap((command) => {
            const path = spec.commandPath(command);
            return path !== undefined && spec.isGeneratedCommand(command) ? [path] : [];
          }),
        );
      }
      return generated as Record<EventName, string[]>;
    },
    documentContainsCommand: (document, command) => {
      const hooks = hooksOf(document);
      return Object.keys(hooks ?? {}).some((eventName) =>
        entriesOf(hooks, eventName).some((entry) => entryHasCommand(entry, command)),
      );
    },
  };
}
