import { access, readFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

describe("provider hook ingress removal guard", () => {
  it("keeps generated provider hook paths off the removed station-hook bridge", async () => {
    const productionFiles = [
      // Claude/Codex/Cursor/Crush hook scripts are now generated by the shared runtime helper
      // rather than per-provider hookScript.ts files; scan it for the removed bridge reference.
      "packages/runtime/src/hookSetup.ts",
      "integrations/worktree/worktrunk/src/hooks.ts",
      "integrations/harness/pi/src/piExtension.ts",
      "package.json",
    ];
    const violations: string[] = [];

    for (const relativePath of productionFiles) {
      const source = await readFile(join(process.cwd(), relativePath), "utf8");
      if (source.includes("station-hook")) {
        violations.push(`${relativePath}: station-hook`);
      }
      if (source.includes("station hook")) {
        violations.push(`${relativePath}: station hook`);
      }
    }

    await expect(access(join(process.cwd(), "bin", "station-hook"))).rejects.toThrow();
    await expect(access(join(process.cwd(), "apps", "hook-runner"))).rejects.toThrow();
    await expect(access(join(process.cwd(), "packages", "hook-bridge"))).rejects.toThrow();
    expect(violations).toEqual([]);
  });
});
