import { expect, it } from "vitest";
import type {
  ClientNotice,
  DashboardActions,
  DashboardCapabilities,
  DashboardExecutionHandle,
  DashboardExecutionResult,
  DashboardFocusTarget,
  DashboardRuntime,
  DashboardRuntimeOptions,
  DashboardStateSource,
  ObserverService,
  OpenDashboardShellRequest,
  StationClientCommandCompletion,
  TuiFolderService,
} from "../../src/entrypoints/runtime.js";
import type {
  CreateGroupActionId,
  CreateGroupControlContent,
  CreateGroupSheetContent,
  DashboardCellId,
  DashboardFilterFooterSegment,
  DashboardFilterHeaderModel,
  DashboardFooterModel,
  DashboardGroupHeaderPayload,
  DashboardPersistentFilterGroupMatch,
  DashboardRowId,
  DashboardSessionRow,
  DashboardSlots,
  DashboardTableHeaderModel,
  DashboardTreeBranch,
  DashboardTreeRow,
  EditableTextInputState,
  FleetSummary,
  GroupOrderingMode,
  RowGridLayout,
} from "../../src/entrypoints/selectors.js";
import type {
  AddProjectFlowStateView,
  CreateGroupFocus,
  CreateGroupReturnTarget,
  CreateGroupScreenView,
  DashboardGroupHeaderActionVisibility,
  DashboardScreenView,
  DashboardSnapshotView,
  DashboardStateView,
  NewSessionFlowStateView,
  ProjectMenuActionId,
  ProjectMenuInputActionId,
  ProjectMenuScreenView,
  TuiInputMode,
  TuiKey,
  TuiSelectionState,
  TuiSemanticAction,
  TuiToastEntry,
} from "../../src/entrypoints/state.js";
import type { TextCellUnit } from "../../src/entrypoints/text.js";
import type {
  TopRowWidgetRuntimeDeps,
  TopRowWidgetView,
  TuiConfig,
  TuiWidgetConfig,
} from "../../src/entrypoints/widgets.js";

it("typechecks the role entrypoint contracts", () => {
  expect(true).toBe(true);
});

export type EntrypointTypecheckWitness = [
  TextCellUnit,
  DashboardRuntime,
  DashboardRuntimeOptions,
  DashboardStateSource,
  DashboardActions,
  DashboardCapabilities,
  DashboardExecutionHandle,
  DashboardExecutionResult,
  DashboardFocusTarget,
  OpenDashboardShellRequest,
  ObserverService,
  ClientNotice,
  StationClientCommandCompletion,
  TuiFolderService,
  DashboardStateView,
  DashboardGroupHeaderActionVisibility,
  DashboardScreenView,
  DashboardSnapshotView,
  TuiKey,
  TuiInputMode,
  TuiSemanticAction,
  TuiSelectionState,
  TuiToastEntry,
  AddProjectFlowStateView,
  NewSessionFlowStateView,
  ProjectMenuActionId,
  ProjectMenuInputActionId,
  ProjectMenuScreenView,
  CreateGroupFocus,
  CreateGroupReturnTarget,
  CreateGroupScreenView,
  DashboardSessionRow,
  DashboardRowId,
  DashboardCellId,
  DashboardTreeRow,
  DashboardGroupHeaderPayload,
  DashboardTreeBranch,
  DashboardPersistentFilterGroupMatch,
  GroupOrderingMode,
  DashboardSlots,
  FleetSummary,
  DashboardTableHeaderModel,
  DashboardFooterModel,
  DashboardFilterHeaderModel,
  DashboardFilterFooterSegment,
  RowGridLayout,
  EditableTextInputState,
  CreateGroupActionId,
  CreateGroupControlContent,
  CreateGroupSheetContent,
  TopRowWidgetView,
  TopRowWidgetRuntimeDeps,
  TuiConfig,
  TuiWidgetConfig,
];
