import { rgbColor, type StationTheme } from "./types.js";

// This file is Station's sole production raw-color authority; renderers consume semantic roles.
const palette = {
  gray: rgbColor("#9ca3af"),
  red: rgbColor("#f87171"),
  yellow: rgbColor("#fbbf24"),
  green: rgbColor("#4ade80"),
  blue: rgbColor("#60a5fa"),
  cyan: rgbColor("#22d3ee"),
  purple: rgbColor("#d2a8ff"),
  foreground: rgbColor("#e4e4e7"),
  background: rgbColor("#101316"),
  hover: rgbColor("#1f242b"),
  overlay: rgbColor("#000000"),
  hairline: rgbColor("#20252c"),
  focus: rgbColor("#15222e"),
  compactFocus: rgbColor("#1b3448"),
  menuSurface: rgbColor("#15191e"),
  menuSelected: rgbColor("#2f3842"),
  menuText: rgbColor("#f4f4f5"),
  menuDisabled: rgbColor("#7a828c"),
  menuBorder: rgbColor("#5b6470"),
  welcomeButton: rgbColor("#1f2937"),
  welcomeButtonHover: rgbColor("#263142"),
  welcomeShimmer: rgbColor("#4a6a8c"),
  welcomeBorder: rgbColor("#3f4750"),
  welcomeMuted: rgbColor("#a1a1aa"),
  white: rgbColor("#ffffff"),
  panePrimaryInactive: rgbColor("#1d4ed8"),
  paneSelection: rgbColor("#264f78"),
  shellGreenActive: rgbColor("#34d399"),
  shellGreenInactive: rgbColor("#14532d"),
  shellPurpleActive: rgbColor("#c084fc"),
  shellPurpleInactive: rgbColor("#581c87"),
  shellYellowInactive: rgbColor("#713f12"),
  shellCyanInactive: rgbColor("#164e63"),
  terminalForeground: rgbColor("#d4d4d8"),
  ansiBlack: rgbColor("#000000"),
  ansiRed: rgbColor("#cd3131"),
  ansiGreen: rgbColor("#0dbc79"),
  ansiYellow: rgbColor("#e5e510"),
  ansiBlue: rgbColor("#2472c8"),
  ansiMagenta: rgbColor("#bc3fbc"),
  ansiCyan: rgbColor("#11a8cd"),
  ansiWhite: rgbColor("#e5e5e5"),
  ansiBrightBlack: rgbColor("#666666"),
  ansiBrightRed: rgbColor("#f14c4c"),
  ansiBrightGreen: rgbColor("#23d18b"),
  ansiBrightYellow: rgbColor("#f5f543"),
  ansiBrightBlue: rgbColor("#3b8eea"),
  ansiBrightMagenta: rgbColor("#d670d6"),
  ansiBrightCyan: rgbColor("#29b8db"),
  ansiBrightWhite: rgbColor("#ffffff"),
} as const;

const terminal = {
  defaultForeground: palette.terminalForeground,
  defaultBackground: palette.background,
  ansi16: [
    palette.ansiBlack,
    palette.ansiRed,
    palette.ansiGreen,
    palette.ansiYellow,
    palette.ansiBlue,
    palette.ansiMagenta,
    palette.ansiCyan,
    palette.ansiWhite,
    palette.ansiBrightBlack,
    palette.ansiBrightRed,
    palette.ansiBrightGreen,
    palette.ansiBrightYellow,
    palette.ansiBrightBlue,
    palette.ansiBrightMagenta,
    palette.ansiBrightCyan,
    palette.ansiBrightWhite,
  ],
} as const;

const sharedRoles = {
  text: {
    primary: palette.foreground,
    muted: palette.gray,
    inverse: palette.background,
    disabled: palette.menuDisabled,
    menu: palette.menuText,
  },
  status: {
    neutral: palette.gray,
    danger: palette.red,
    warning: palette.yellow,
    success: palette.green,
    working: palette.blue,
    info: palette.blue,
    accent: palette.purple,
  },
  action: {
    primary: palette.cyan,
    success: palette.green,
    danger: palette.red,
    warning: palette.yellow,
  },
  interaction: {
    hover: palette.hover,
    keyboardFocus: palette.focus,
    compactFocus: palette.compactFocus,
    border: palette.gray,
    hairline: palette.hairline,
  },
  welcome: {
    button: palette.welcomeButton,
    buttonMuted: palette.background,
    buttonHover: palette.welcomeButtonHover,
    shimmer: palette.welcomeShimmer,
    border: palette.welcomeBorder,
    borderActive: palette.blue,
    muted: palette.welcomeMuted,
    wordmark: palette.menuText,
    shimmerPeak: palette.white,
  },
  contextMenu: {
    surface: palette.menuSurface,
    selected: palette.menuSelected,
    border: palette.menuBorder,
  },
  island: {
    background: palette.background,
    resting: palette.green,
    expanded: palette.blue,
    attention: palette.red,
    actionable: palette.purple,
  },
  pane: {
    primary: { active: palette.blue, inactive: palette.panePrimaryInactive },
    shells: [
      { active: palette.shellGreenActive, inactive: palette.shellGreenInactive },
      { active: palette.shellPurpleActive, inactive: palette.shellPurpleInactive },
      { active: palette.yellow, inactive: palette.shellYellowInactive },
      { active: palette.cyan, inactive: palette.shellCyanInactive },
    ],
    selection: palette.paneSelection,
  },
  terminal,
} as const;

export const nativeStationTheme = {
  ...sharedRoles,
  surfaces: {
    canvas: palette.background,
    panel: palette.background,
    prompt: palette.background,
    help: palette.overlay,
    sheet: palette.background,
    settings: palette.background,
    toast: palette.background,
  },
} as const satisfies StationTheme;
