name: Bump Homebrew formula

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  bump-formula:
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@ccf2332299a883f6af50a1d2d41e5df7904dd769 # v4.1
        with:
          formula-name: station
          homebrew-tap: jeremy0dell/homebrew-station
          push-to: jeremy0dell/homebrew-station
          tag-name: ${{ github.event.release.tag_name }}
          download-url: https://github.com/jeremy0dell/station.git
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
